
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_web_api from "./scripts/web-api";
import * as scripts_notifications from "./scripts/notifications";
import * as scripts_game from "./scripts/game";
import * as scripts_bounding_box_updater from "./scripts/bounding-box-updater";
import * as scripts_text_block from "./scripts/text-block";
import * as scripts_input_field from "./scripts/input-field";
import * as scripts_text_block from "./scripts/text-block";

export const scriptsMap = {
    "scripts/ui.ts": scripts_ui,
	"scripts/web-api.ts": scripts_web_api,
	"scripts/notifications.ts": scripts_notifications,
	"scripts/game.ts": scripts_game,
	"scripts/bounding-box-updater.ts": scripts_bounding_box_updater,
	"scripts/text-block.ts": scripts_text_block,
	"scripts/input-field.ts": scripts_input_field
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
