
/**
 * Generated by Babylon.js Editor
 */

import { loadScene } from "babylonjs-editor-tools";

export const scriptsMap = {
    "scripts/ui.ts": require("@/scripts/ui"),
	"scripts/text-block.ts": require("@/scripts/text-block")
};

export { loadScene };
